CREATE TABLE Users
(
    HoTen NVARCHAR(50) NULL,
    NamSinh NVARCHAR(50) NOT NULL,
    Email NVARCHAR(50) PRIMARY KEY,
    SoDienThoai NVARCHAR(15) NOT NULL,
    MatKhau NVARCHAR(50) NOT NULL,
    MaCode NVARCHAR(15) NULL
);